name: Kallisto

on:
  push:
    branches: [ "main" ]
    paths:
      - modules/module_4/notebooks/RNA-Seq_pseudoalignment.sh
      - .github/workflows/run_kallisto.yml
  pull_request:
    paths:
      - modules/module_4/notebooks/RNA-Seq_pseudoalignment.sh
      - .github/workflows/run_kallisto.yml
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

jobs:
  jupyter-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"

      - name: Install dependencies
        run: |
          conda install -y -c bioconda multiqc fastqc kallisto igv
          pip install ffq gget

      - name: Run
        run: |
          cd modules/module_4/notebooks
          chmod +x RNA-Seq_pseudoalignment.sh
          ./RNA-Seq_pseudoalignment.sh
